ALTER DATABASE SH_MyBase ADD FILEGROUP FG1;
ALTER DATABASE SH_MyBase ADD FILE 
( NAME = N'SH_MyBase1', FILENAME = N'D:\temp\SH_MyBase1.ndf', SIZE = 8192KB, MAXSIZE = 2048GB , FILEGROWTH = 65536KB) 
TO FILEGROUP FG1;
ALTER DATABASE SH_MyBase MODIFY FILEGROUP FG1 DEFAULT;